<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>8bc1fe66-475b-4c20-bbfb-04057475cf80</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set amountSpent to 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
