<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>ServiceVerificationBR</name>
  <uuid>5e26985f-749e-4007-bbfa-590a888e33c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	number2 is "H" 
	and number1 is "L" 
then
	set decision to "Hello" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
