<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>BR</name>
  <uuid>7488ccfe-a863-4a43-acf0-e7873bf77e21</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is "1" 
then
	set decision to "Good" ;
    else
    set decision to "Bad" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
